"""Pydantic models for API schemas."""

from .api_key import (
    APIKeyCreate,
    APIKeyUpdate,
    APIKeyResponse,
    APIKeyCreateResponse,
    APIKeyUsageStats,
    APIKeyListResponse,
    APIKeyRotateResponse,
    APIKeyDeleteResponse,
    APIKeyValidationError,
    RateLimitInfo,
)
from .auth import (
    UserRegistration,
    UserLogin,
    TokenResponse,
    TokenRefresh,
    UserProfile,
    UserUpdate,
    LoginResponse,
    RegistrationResponse,
    LogoutResponse,
    AuthStatus,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    EmailVerification,
    SuccessResponse,
    ErrorResponse,
)

__all__ = [
    # API Key models
    "APIKeyCreate",
    "APIKeyUpdate",
    "APIKeyResponse",
    "APIKeyCreateResponse",
    "APIKeyUsageStats",
    "APIKeyListResponse",
    "APIKeyRotateResponse",
    "APIKeyDeleteResponse",
    "APIKeyValidationError",
    "RateLimitInfo",
    # Auth models
    "UserRegistration",
    "UserLogin", 
    "TokenResponse",
    "TokenRefresh",
    "UserProfile",
    "UserUpdate",
    "LoginResponse",
    "RegistrationResponse",
    "LogoutResponse",
    "AuthStatus",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "EmailVerification",
    "SuccessResponse",
    "ErrorResponse",
]